//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @MvcFramework.Biz.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using Infrastructure.Core.BaseClasses;
    
    public partial class AuditLog : IEntityIdentity 
    {
    
    	[Required]
        public int Id { get; set; }
    
    	[Required]
    	[StringLength(50)]
        public string Operation { get; set; }
    
    	[Required]
    	[StringLength(250)]
        public string EntityName { get; set; }
    
    	[StringLength(1000)]
        public string EntityPKNames { get; set; }
    
    	[StringLength(1000)]
        public string EntityPKValues { get; set; }
    
    	[StringLength(50)]
        public string PropertyName { get; set; }
    
    	[StringLength(1000)]
        public string OriginalValue { get; set; }
    
    	[StringLength(1000)]
        public string CurrentValue { get; set; }
    
    	[Required]
        public System.DateTime CreatedDateTimeUTC { get; set; }
    
    	[Required]
        public int UserId { get; set; }
    
    	
        /// <summary>
        /// Read only access to the primary key - used for Upserts
        /// </summary>
    	public int PrimaryKeyValue
        {
            get
            {
                return Id;
            }
        }
    
        public virtual User Users { get; set; }
    }
}
