//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @MvcFramework.Biz.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using Infrastructure.Core.BaseClasses;
    
    public partial class ELMAHError 
    {
    
    	[Required]
        public System.Guid ErrorId { get; set; }
    
    	[Required]
    	[StringLength(60)]
        public string Application { get; set; }
    
    	[Required]
    	[StringLength(50)]
        public string Host { get; set; }
    
    	[Required]
    	[StringLength(100)]
        public string Type { get; set; }
    
    	[Required]
    	[StringLength(60)]
        public string Source { get; set; }
    
    	[Required]
    	[StringLength(500)]
        public string Message { get; set; }
    
    	[Required]
    	[StringLength(50)]
        public string User { get; set; }
    
    	[Required]
        public int StatusCode { get; set; }
    
    	[Required]
        public System.DateTime TimeUtc { get; set; }
    
    	[Required]
        public int Sequence { get; set; }
    
    	[Required]
        public string AllXml { get; set; }
    }
}
