//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @MvcFramework.Biz.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using Infrastructure.Core.BaseClasses;
    
    public partial class User : IEntityIdentity 
    {
       	[DebuggerStepThrough]
    	public User()
        {
            this.Roles = new HashSet<Role>();
            this.AuditLog = new HashSet<AuditLog>();
        }
    
    
    	[Required]
        public int UserID { get; set; }
    
    	[Required]
    	[StringLength(256)]
        public string Username { get; set; }
    
    	[StringLength(256)]
        public string Email { get; set; }
    
    	[Required]
        public bool IsAnonymous { get; set; }
    
    	[Required]
        public System.DateTime LastActivityDate { get; set; }
    
    	[Required]
    	[StringLength(128)]
        public string Password { get; set; }
    
    	[Required]
        public int PasswordFormat { get; set; }
    
    	[Required]
    	[StringLength(128)]
        public string PasswordSalt { get; set; }
    
    	[StringLength(128)]
        public string PasswordQuestion { get; set; }
    
    	[StringLength(128)]
        public string PasswordAnswer { get; set; }
    
    	[Required]
        public bool IsApproved { get; set; }
    
    	[Required]
        public System.DateTime CreateOn { get; set; }
    
    	[Required]
        public System.DateTime LastLoginDate { get; set; }
    
    	[Required]
        public System.DateTime LastPasswordChangedDate { get; set; }
    
    	[Required]
        public System.DateTime LastLockoutDate { get; set; }
    
    	[Required]
        public int FailedPasswordAttemptCount { get; set; }
    
    	[Required]
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    
    	[Required]
        public int FailedPasswordAnswerAttemptCount { get; set; }
    
    	[Required]
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
    
    	[Required]
        public string Comment { get; set; }
    
    	[StringLength(100)]
        public string FirstName { get; set; }
    
    	[StringLength(100)]
        public string LastName { get; set; }
    
        public Nullable<int> TimeZone { get; set; }
    
    	[Required]
        public byte Status { get; set; }
    
    	[Required]
        public int ApplicationID { get; set; }
    
    	
        /// <summary>
        /// Read only access to the primary key - used for Upserts
        /// </summary>
    	public int PrimaryKeyValue
        {
            get
            {
                return UserID;
            }
        }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<AuditLog> AuditLog { get; set; }
    }
}
